version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      myst_parser

sphinx:
  configuration: docs/source/conf.py
  
formats:
  - pdf
  - epub
